import { FiFileText, FiChevronLeft, FiChevronRight, FiDownload } from 'react-icons/fi'
import styles from './styles.module.css'

function RecentReports({ reports = [] }) {
	return <section className={styles.panel}><header><h2><FiFileText style={{ marginRight: '8px', verticalAlign: 'middle' }} /> Recent Reports</h2></header><table><thead><tr><th>Report Name</th><th>Category</th><th>Date Generated</th><th>Generated By</th><th>Format</th><th>Action</th></tr></thead><tbody>{reports.map((report) => <tr key={report.id}><td>{report.name}</td><td>{report.category}</td><td>{new Date(report.created_at).toLocaleString()}</td><td>{report.created_by || 'Admin'}</td><td><em>{report.format}</em></td><td><FiDownload /></td></tr>)}</tbody></table><footer>Showing {reports.length} reports <span><FiChevronLeft /> <strong>1</strong> <FiChevronRight /></span></footer></section>
}

export default RecentReports
